"use strict";

const BASE_URL = window.location.protocol + '//' + window.location.host;
const PATH_URL = window.location.pathname;
const FULL_URL = window.location.href;
const GET_PARAM = key => {
  return new URL(FULL_URL).searchParams.get(key);
};
const SETTING = {
  api: {
    compatibility: 'https://www.apiipaapiipa.pp.ua/api/foodInteractions',
    instructions: 'https://dev-client-node.red.a911.ua/getInstructionDrug',
    translation: 'https://dev-client-node.red.a911.ua/translation',
    log: 'https://dev-client-node.red.a911.ua/drugInteractionLogs',
    logInstructions: 'https://dev-client-node.red.a911.ua/clickInstructionDrug',
    timeout: 15000,
    timeoutTranslation: 10000,
    delay: 2000,
    delayTranslation: 2000
  },
  examples: ['Бісопролол,Верапаміл', 'Аспірин'],
  defaultLanguage: GET_PARAM('language') || sessionStorage.getItem('language') || 'uk',
  language: {
    uk: {
      uk: 'Українська',
      ru: 'Російська',
      en: 'Англійська',
      original: 'Мова оригіналу',
      api_error_alert: 'Виникла невідома помилка! Спробуйте перезавантажити сторінку.',
      autocomplete_not_found: 'За Вашим запитом результатів не має',
      input_required: 'Обов’язкове поле',
      check: 'Перевірити',
      clear: 'Очистити',
      show_example: 'Переглянути приклад',
      show_another_example: 'Інший приклад',
      input_drug: 'Напишіть препарат або діючу речовину',
      input_drug_required: '* Напишіть препарат або діючу речовину',
      logo: 'Взаємодія<br>препаратів',
      change_lang: 'Змінити мову',
      select_lang: 'Обрати мову',
      drug: 'Лікарський засіб',
      alcohol: 'Алкоголь',
      food: 'Їжа',
      caffeine: 'Кофеїн',
      instructions: 'Від виробника',
      tab_input_drugs: 'Напишіть назви препаратів або діючих речовин у рядках вище, щоб перевірити взаємодію.',
      tab_input_second_drug: 'Напишіть другий препарат або діючу речовину, щоб перевірити взаємодію препаратів.',
      tab_not_fount_drugs: 'Інформацію щодо взаємодії препаратів не знайдено.',
      tab_not_fount_alcohol: 'Інформацію щодо взаємодії з алкоголем не знайдено.',
      tab_not_fount_food: 'Інформацію щодо взаємодії з їжею не знайдено.',
      tab_not_fount_caffeine: 'Інформацію щодо взаємодії з кофеїном не знайдено.',
      show_more: 'Читати далі...',
      show_less: 'Сховати...',
      source: 'Джерело',
      is_searching: 'Пошук інформації',
      is_translating: 'Перекладаємо',
      tour_name: 'Навчання',
      tour_prev: 'Назад',
      tour_next: 'Далі',
      tour_finish: 'Все зрозуміло',
      tour_skip: 'Пропустити',
      tour_step_0: 'Пройдіть коротке навчання по використанню сервісу взаємодії препаратів',
      tour_step_1: 'Введіть назву препарату в перший рядок пошуку',
      tour_step_2: 'Ви можете додати ще одну назву, для перевірки взаємодії препаратів, або перевірити лише один препарат',
      tour_step_3: 'Натисніть кнопку “Перевірити”',
      tour_step_4: 'Ознайомтеся з інформацією про взаємодію',
      tour_step_5: 'Перевіряйте взаємодію з алкоголем, їжею, кофеїном, натискаючи вкладинки',
      tour_step_6: 'Ви можете змінити мову для відображення тексту про взаємодію',
      tour_step_7: 'Наприклад, можете обрати англійську мову',
      tour_step_8: 'Статті перекладені на англійську мову'
    },
    ru: {
      uk: 'Украинский',
      ru: 'Русский',
      en: 'Английский',
      original: 'Язык оригинала',
      api_error_alert: 'Произошла неизвестная ошибка! Попробуйте перезагрузить страницу.',
      autocomplete_not_found: 'По Вашему запросу результатов нет',
      input_required: 'Обязательное поле',
      check: 'Проверить',
      clear: 'Очистить',
      show_example: 'Посмотреть пример',
      show_another_example: 'Другой пример',
      input_drug: 'Напишіть препарат або діючу речовину',
      input_drug_required: '* Напишіть препарат або діючу речовину',
      logo: 'Взаимодействие<br>препаратов',
      change_lang: 'Изменить язык',
      select_lang: 'Выбрать язык',
      drug: 'Лекарственное средство',
      alcohol: 'Алкоголь',
      food: 'Еда',
      caffeine: 'Кофеин',
      instructions: 'От производителя',
      tab_input_drugs: 'Напишите названия препаратов или действующих веществ в строках выше, чтобы проверить взаимодействие.',
      tab_input_second_drug: 'Напишите второй препарат или действующее вещество, чтобы проверить взаимодействие препаратов.',
      tab_not_fount_drugs: 'Информацию о взаимодействии препаратов не найдено.',
      tab_not_fount_alcohol: 'Информацию о взаимодействии с алкоголем не найдено.',
      tab_not_fount_food: 'Информацию о взаимодействии с едой не найдено.',
      tab_not_fount_caffeine: 'Информацию о взаимодействии с кофеином не найдено.',
      show_more: 'Читать дальше...',
      show_less: 'Спрятать...',
      source: 'Источник',
      is_searching: 'Поиск информации',
      is_translating: 'Переводим',
      tour_name: 'Обучение',
      tour_prev: 'Назад',
      tour_next: 'Далее',
      tour_finish: 'Все понятно',
      tour_skip: 'Пропустить',
      tour_step_0: 'Пройдите короткое обучение по использованию сервиса взаимодействия препаратов',
      tour_step_1: 'Введите название препарата в первый рядок поиска',
      tour_step_2: 'Вы можете добавить еще одно название, для проверки взаимодействия препаратов, или проверить только один препарат',
      tour_step_3: 'Нажмите кнопку “Проверить”',
      tour_step_4: 'Ознакомьтесь с информацией о взаимодействии',
      tour_step_5: 'Проверяйте взаимодействие с алкоголем, едой, кофеином, нажимая вкладки',
      tour_step_6: 'Ви можете изменить язык для отображения текста о взаимодействии',
      tour_step_7: 'Например, можете выбрать английский язык',
      tour_step_8: 'Статьи переведены на английский	язык'
    },
    en: {
      uk: 'Ukrainian',
      ru: 'Russian',
      en: 'English',
      original: 'Original language',
      api_error_alert: 'Произошла неизвестная ошибка! Попробуйте перезагрузить страницу.',
      autocomplete_not_found: 'No results for your request',
      input_required: 'Obligatory field',
      check: 'Check out',
      clear: 'Clear',
      show_example: 'Show example',
      show_another_example: 'Another example',
      input_drug: 'Write the drug or active ingredient',
      input_drug_required: '* Write the drug or active ingredient',
      logo: 'Drug<br>interactions',
      change_lang: 'Change language',
      select_lang: 'Select language',
      drug: 'Medicinal product',
      alcohol: 'Alcohol',
      food: 'Food',
      caffeine: 'Caffeine',
      instructions: 'From manufacturer',
      tab_input_drugs: 'Write the names of the drugs or active substances on the lines above to check the interaction.',
      tab_input_second_drug: 'Write a second drug or active ingredient to check drug interactions.',
      tab_not_fount_drugs: 'No information on drug interactions was found.',
      tab_not_fount_alcohol: 'No information on interaction with alcohol was found.',
      tab_not_fount_food: 'No information on interaction with food was found.',
      tab_not_fount_caffeine: 'No information on interaction with caffeine was found.',
      show_more: 'Read more...',
      show_less: 'Hide...',
      source: 'Source',
      is_searching: 'Searching',
      is_translating: 'Translating',
      tour_name: 'Навчання',
      tour_prev: 'Назад',
      tour_next: 'Далі',
      tour_finish: 'Все зрозуміло',
      tour_skip: 'Пропустити',
      tour_step_0: 'Пройдіть коротке навчання по використанню сервісу взаємодії препаратів',
      tour_step_1: 'Введіть назву препарату в перший рядок пошуку',
      tour_step_2: 'Ви можете додати ще одну назву, для перевірки взаємодії препаратів, або перевірити лише один препарат',
      tour_step_3: 'Натисніть кнопку “Перевірити”',
      tour_step_4: 'Ознайомтеся з інформацією про взаємодію',
      tour_step_5: 'Перевіряйте взаємодію з алкоголем, їжею, кофеїном, натискаючи вкладинки',
      tour_step_6: 'Ви можете змінити мову для відображення тексту про взаємодію',
      tour_step_7: 'Наприклад, можете обрати англійську мову',
      tour_step_8: 'Статті перекладені на англійську мову'
    }
  },
  icon: {
    close: '<svg width="18" height="19" viewBox="0 0 18 19" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 1.68188L1 17.6819" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M1 1.68188L17 17.6819" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>	',
    comparison: '<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_106_2316)"><path d="M2.5 14.1667L17.5 14.1667" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M5 11.6667L2.5 14.1667L5 16.6667" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M15 3.33325L17.5 5.83325L15 8.33325" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M17.5 5.83325L2.5 5.83325" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="clip0_106_2316"><rect width="20" height="20" transform="matrix(0 -1 1 0 0 20)"/></clipPath></defs></svg>',
    arrowLeft: '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_586_3843)"><path d="M12.667 8H3.33366" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M7.33301 12L3.33301 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M7.33301 4L3.33301 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="clip0_586_3843"><rect width="16" height="16" transform="matrix(-1 0 0 1 16 0)"/></clipPath></defs></svg>',
    arrowRight: '<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_585_510)"><path d="M3.33301 8H12.6663" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.66699 12L12.667 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.66699 4L12.667 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="clip0_585_510"><rect width="16" height="16"/></clipPath></defs></svg>'
  },
  tour: {
    drugs: [{
      answer: {},
      source: 'https://combomed.ru',
      language: 'uk',
      drug_1: 'Бісопролол',
      drug_2: 'Верапаміл',
      text: 'При одночасному застосуванні антигіпертензивних засобів можливе посилення антигіпертензивної дії. Препарати кальцію знижують ефективність застосування верапамілу. Рифампіцин, барбітурати, нікотин, прискорюючи метаболізм у печінці, призводять до зниження концентрації верапамілу в крові, зменшують вираженість антиангінальної, гіпотензивної та антиаритмічної дії.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Верапаміл',
      text: 'Антагоністи кальцію (групи верапамілу, меншою мірою - дилтіазему): негативний вплив на скорочувальну функцію міокарда та AV-провідність. Введення верапамілу у пацієнтів, які приймають β-блокатори, може призвести до вираженої артеріальної гіпотензії та AV блокади. міокарда та порушення AV провідності. Не рекомендується внутрішньовенне введення верапамілу/дилтіазему пацієнтам, які приймають бета-адреноблокатори, оскільки це може призвести до вираженої артеріальної гіпотензії та AV-блокади. та інші антиаритмічні засоби підвищують ризик розвитку або посилення брадикардії, AV блокади, зупинки серця та серцевої недостатності. Блокатори кальцієвих каналів з групи верапамілу та меншою мірою – з групи дилтіазему. Введення верапамілу пацієнтам, які отримують терапію бета-адреноблокаторами, може супроводжуватися розвитком вираженої артеріальної гіпотензії та AV блокади. Блокатори кальцієвих каналів дигідропіридинового типу (наприклад фелодипін та амлодипін). Не можна виключити, що поєднане застосування може збільшити ризик гіпотензії та зниження насосної функції шлуночка у пацієнтів із серцевою недостатністю.',
      backupText: ''
    }],
    alcohol: [{
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Алкоголь',
      text: 'Трициклічні та тетрациклічні антидепресанти, антипсихотичні засоби (нейролептики), етанол, седативні та снодійні засоби посилюють пригнічення центральної нервової системи. - та тетрациклічні антидепресанти, антипсихотичні засоби (нейролептики), етанол, седативні та снодійні лікарські засоби посилюють пригнічення центральної нервової системи. Не рекомендується одночасне застосування Бісопрололу з інгібіторами МАО (крім МАО-В) внаслідок значного посилення гіпотензивної дії. Перерва у лікуванні між прийомом інгібіторів МАО та Бісопрололу має становити не менше 14 днів.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Верапаміл',
      drug_2: 'Алкоголь',
      text: 'При одночасному застосуванні верапаміл підвищує концентрацію етанолу в плазмі крові та подовжує його ефект. Підвищує концентрацію теофіліну (внаслідок зниження кліренсу), етанолу (і подовжує його ефект), концентрацію хінідину (ризик вираженого зниження АТ, особливо у пацієнтів з ІГСС). (алкоголь)\nПідвищення концентрації етанолу в плазмі крові та уповільнення його виведення. Тому вплив етанолу може бути посилено. Підвищує концентрацію теофіліну (внаслідок зниження кліренсу), етанолу (і подовжує його ефект), концентрацію хінідину (ризик вираженого зниження АТ, особливо у пацієнтів з ІГСС). Може підвищувати концентрацію аторвастатину та ловастатину при одночасному застосуванні.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://drugs.com',
      language: 'en',
      drug_1: 'Верапаміл',
      drug_2: 'Алкоголь',
      text: 'ЗАГАЛОМ УНИКАЙТЕ: Верапаміл може підвищити концентрацію в крові та інтоксикаційну дію етанолу. Точний механізм взаємодії невідомий, але він може включати верапаміл у пригнічення метаболізму етанолу. У 10 здорових молодих добровольців верапаміл (80 мг перорально кожні 8 годин протягом 6 днів) підвищував середню пікову концентрацію в крові (Cmax) і 12-годинну площу під кривою концентрація-час (AUC) етанолу (0,8 г/кг). разової пероральної дози) на 17% і 30% відповідно порівняно з плацебо. Значення AUC верапамілу позитивно корелювали зі збільшенням значень AUC етанолу в крові. Суб’єктивно (тобто сприйняття сп’яніння кожним суб’єктом, виміряне за візуальною аналоговою шкалою), верапаміл також значно збільшив площу під кривою залежності ефекту етанолу від часу, але не змінив пік ефекту або час до піку ефекту.<br>\n<br >\nДОТРИМАННЯ: Пацієнтам, які отримують верапаміл, слід порадити уникати вживання алкоголю.',
      backupText: ''
    }],
    food: [{
      answer: {},
      source: 'https://drugs.com',
      language: 'en',
      drug_1: 'Верапаміл',
      drug_2: 'Їжа',
      text: 'ЗАГАЛОМ УНИКАЙТЕ: споживання великої кількості грейпфрутового соку може бути пов’язане зі значним підвищенням концентрації перорального верапамілу в плазмі крові. Механізм полягає в інгібуванні CYP450 3A4-опосередкованого метаболізму першого проходження в стінці кишечника певними сполуками, присутніми в грейпфрутах. В одному дослідженні не було виявлено істотного впливу одноразового прийому грейпфрутового соку на фармакокінетику верапамілу у десяти пацієнтів з гіпертонією, які отримували тривалу терапію. В іншому дослідженні, проведеному за участю дев’яти здорових добровольців чоловічої статі, пероральний прийом 120 мг верапамілу двічі на день протягом 3 днів після попереднього прийому 200 мл грейпфрутового соку двічі на день протягом 5 днів призводив до підвищення пікової концентрації S-верапамілу в плазмі (Cmax) на 57%, збільшення системної експозиції (AUC) S-верапамілу на 36%, Cmax R-верапамілу на 40% і AUC R-верапамілу на 28% порівняно із застосуванням після апельсинового соку.',
      backupText: ''
    }],
    caffeine: [{
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Кофеїн',
      text: "Кліренс лідокаїну та ксантинів (крім теофіліну) може знижуватися у зв'язку з можливим підвищенням їх концентрації в плазмі крові, особливо у пацієнтів з вихідно підвищеним кліренсом теофіліну під впливом куріння. підвищення АТ). Знижує кліренс лідокаїну та ксантинів (крім дифіліну) і підвищує їх концентрацію в плазмі, особливо у хворих з вихідно підвищеним кліренсом теофіліну під впливом куріння. вихідно підвищеним кліренсом теофіліну під впливом куріння. Знижує кліренс лідокаїну та ксантинів, і підвищує їх концентрацію в плазмі, особливо у хворих з вихідно підвищеним кліренсом теофіліну під впливом куріння. з адренергічними бронхорозширювальними ЛЗ – до додаткової стимуляції ЦНС та ін. адитивним токсичним ефектам.",
      backupText: ''
    }]
  },
  tour_translated: {
    drugs: [{
      answer: {},
      source: 'https://combomed.ru',
      language: 'uk',
      drug_1: 'Бісопролол',
      drug_2: 'Верапаміл',
      text: 'With the simultaneous use of antihypertensive agents, an increase in the antihypertensive effect is possible. Calcium preparations reduce the effectiveness of verapamil. Rifampicin, barbiturates, nicotine, accelerating metabolism in the liver, lead to a decrease in the concentration of verapamil in the blood, reduce the severity of antianginal, hypotensive and antiarrhythmic effects.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Верапаміл',
      text: 'Calcium antagonists (groups of verapamil, to a lesser extent - diltiazem): negative effect on the contractile function of the myocardium and AV conduction. The administration of verapamil in patients taking β-blockers can lead to pronounced arterial hypotension and AV block. myocardium and AV conduction disorders. Intravenous administration of verapamil/diltiazem is not recommended in patients taking beta-adrenergic blockers, as it may lead to severe hypotension and AV block. and other antiarrhythmic agents increase the risk of developing or worsening bradycardia, AV blockade, cardiac arrest, and heart failure. Calcium channel blockers from the verapamil group and, to a lesser extent, from the diltiazem group. Administration of verapamil to patients receiving therapy with beta-adrenergic blockers may be accompanied by the development of pronounced arterial hypotension and AV blockade. Blockers of calcium channels of the dihydropyridine type (for example, felodipine and amlodipine). It cannot be excluded that the combined use may increase the risk of hypotension and a decrease in the pumping function of the ventricle in patients with heart failure.',
      backupText: ''
    }],
    alcohol: [{
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Алкоголь',
      text: 'Tricyclic and tetracyclic antidepressants, antipsychotics (neuroleptics), ethanol, sedatives and hypnotics increase depression of the central nervous system. - and tetracyclic antidepressants, antipsychotics (neuroleptics), ethanol, sedatives and hypnotic drugs increase depression of the central nervous system. The simultaneous use of Bisoprolol with MAO inhibitors (except MAO-B) is not recommended due to a significant increase in the hypotensive effect. The break in treatment between taking MAO inhibitors and Bisoprolol should be at least 14 days.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Верапаміл',
      drug_2: 'Алкоголь',
      text: 'With simultaneous use, verapamil increases the concentration of ethanol in the blood plasma and prolongs its effect. Increases the concentration of theophylline (due to a decrease in clearance), ethanol (and prolongs its effect), the concentration of quinidine (the risk of a marked decrease in blood pressure, especially in patients with ICS). (alcohol)\nIncreasing the concentration of ethanol in the blood plasma and slowing down its excretion. Therefore, the effect of ethanol can be increased. Increases the concentration of theophylline (due to a decrease in clearance), ethanol (and prolongs its effect), the concentration of quinidine (the risk of a marked decrease in blood pressure, especially in patients with ICS). May increase the concentration of atorvastatin and lovastatin when used simultaneously.',
      backupText: ''
    }, {
      answer: {},
      source: 'https://drugs.com',
      language: 'en',
      drug_1: 'Верапаміл',
      drug_2: 'Алкоголь',
      text: "GENERALLY AVOID:  Verapamil may increase the blood concentrations and intoxicating effects of ethanol.  The exact mechanism of interaction is unknown but may involve verapamil inhibition of ethanol metabolism.  In 10 healthy, young volunteers, verapamil (80 mg orally every 8 hours for 6 days) increased the mean peak blood concentration (Cmax) and the 12-hour area under the concentration-time curve (AUC) of ethanol (0.8 g/kg single oral dose) by 17% and 30%, respectively, compared to placebo.  Verapamil AUCs were positively correlated to increased ethanol blood AUC values.  Subjectively (i.e. each subject's perception of intoxication as measured on a visual analog scale), verapamil also significantly increased the area under the ethanol effect versus time curve but did not change the peak effect or time to peak effect.<br>\n<br>\nMANAGEMENT:  Patients treated with verapamil should be counseled to avoid alcohol consumption.",
      backupText: ''
    }],
    food: [{
      answer: {},
      source: 'https://drugs.com',
      language: 'en',
      drug_1: 'Верапаміл',
      drug_2: 'Їжа',
      text: "GENERALLY AVOID:  Consumption of large quantities of grapefruit juice may be associated with significantly increased plasma concentrations of oral verapamil.  The mechanism is inhibition of CYP450 3A4-mediated first-pass metabolism in the gut wall by certain compounds present in grapefruits.  One study reported no significant effect of a single administration of grapefruit juice on the pharmacokinetics of verapamil in ten hypertensive patients receiving chronic therapy.  In another study conducted in nine healthy male volunteers, administration of 120 mg oral verapamil twice daily for 3 days following pretreatment with 200 mL grapefruit juice twice daily for 5 days resulted in a 57% increase in S-verapamil peak plasma concentration (Cmax), a 36% increase in S-verapamil systemic exposure (AUC), a 40% increase in R-verapamil Cmax, and a 28% increase in R-verapamil AUC compared to administration following orange juice.  Elimination half-life and renal clearance of both S- and R-verapamil were not affected by grapefruit juice, and there were no significant effects on blood pressure, heart rate, or PR interval.  A third study reported a 1.63-fold increase in Cmax and a 1.45-fold increase in AUC of (R,S)-verapamil in 24 young, healthy volunteers given verapamil sustained-release 120 mg twice daily for 7 days with 250 mL grapefruit juice four times daily on days 5 through 7.  Two subjects developed PR interval prolongation of more than 350 ms during grapefruit juice coadministration.  A high degree of interindividual variability has been observed in these studies.  The interaction was also suspected in a case report of a 42-year-old woman who developed complete heart block, hypotension, hypoxic respiratory failure, severe anion gap metabolic acidosis, and hyperglycemia following accidental ingestion of three verapamil sustained-release 120 mg tablets over a span of six hours.  The patient's past medical history was remarkable only for migraine headaches, for which she was receiving several medications including verapamil.  Prior to admission, the patient had a 2-week history of poorly controlled migraine, and the six hours preceding hospitalization she suffered from worsening headache and palpitations progressing to altered sensorium.  An extensive workup revealed elevated verapamil and norverapamil levels more than 4.5 times above the upper therapeutic limits.  These levels also far exceeded those reported in the medical literature for patients taking verapamil 120 mg every 6 hours, or 480 mg in a 24-hour period.  The patient recovered after receiving ventilator and vasopressor support.  Upon questioning, it was discovered that the patient had been drinking large amounts of grapefruit juice (3 to 4 liters total) the week preceding her admission due to nausea.  No other sources or contributing factors could be found for the verapamil toxicity.<br>\n<br>\nMANAGEMENT:  Patients treated with oral verapamil should avoid the consumption of large amounts of grapefruit or grapefruit juice to prevent any undue fluctuations in serum drug levels.  Patients should be advised to seek medical attention if they experience edema or swelling of the lower extremities; sudden, unexplained weight gain; difficulty breathing; chest pain or tightness; or hypotension as indicated by dizziness, fainting, or orthostasis.",
      backupText: ''
    }],
    caffeine: [{
      answer: {},
      source: 'https://checkmed.info',
      language: 'ru',
      drug_1: 'Бісопролол',
      drug_2: 'Кофеїн',
      text: 'The clearance of lidocaine and xanthines (except theophylline) may decrease due to a possible increase in their concentration in the blood plasma, especially in patients with initially increased clearance of theophylline under the influence of smoking. blood pressure increase). Reduces the clearance of lidocaine and xanthines (except diphylline) and increases their concentration in plasma, especially in patients with initially increased clearance of theophylline under the influence of smoking. initially increased clearance of theophylline under the influence of smoking. Reduces the clearance of lidocaine and xanthines, and increases their concentration in plasma, especially in patients with initially increased clearance of theophylline under the influence of smoking. with adrenergic bronchodilators - for additional stimulation of the central nervous system, etc. additive toxic effects.',
      backupText: ''
    }]
  }
};
SETTING.language.original = SETTING.language.uk;